steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gka-standalone/my-docker-repo/my-image', '.']
logsBucket: 'gs://gka-standalone_cloudbuild'
options:
  logging: CLOUD_LOGGING_ONLY